apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.Ingress.name }}
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  ingressClassName: {{ .Values.Ingress.name }}
  rules:
  - http:
      paths:
      - path: {{ .Values.Ingress.path }}
        pathType: {{ .Values.Ingress.pathType }}
        backend:
          service:
            name: {{ .Values.LoadBalancer.name }}
            port:
              number: {{ .Values.LoadBalancer.port }}