apiVersion: v2
kind: Service
metadata:
  name: { .Values.LoadBalancer.name }
spec:
  selector:
    app: {{ .Values.Deployment.app }}
  ports:
    - protocol: {{ .Values.LoadBalancer.protocol }}
      port: {{ .Values.LoadBalancer.port }}
      targetPort: {{ .Values.Loadbalancer.targetPort }}
  type: LoadBalancer